version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 /app/main.py
    ports:
      - 80:80
    volumes:
      - .:/app
    tty: True
  slack:
    build:
      context: .
      dockerfile: ./Dockerfile_slack
  react-app:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    volumes:
      - ../frontend:/usr/src/app # ローカルをコンテナ内にマウント
    command: yarn start
    ports:
      - 3000:3000
    stdin_open: true 
