version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 /app/main.py
    ports:
      - 80:80
    volumes:
      - .:/app
    tty: True
  slack:
    build:
      context: .
      dockerfile: ./Dockerfile_slack
        


