FROM python

RUN apt update -y \
&& apt upgrade -y \
&& apt install -y vim git


RUN pip3 install  -U pip slack slack_sdk aiohttp requests
RUN pip3 install schedule
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
RUN pip3 install thop scipy seaborn joblib matplotlib
RUN pip3 install pandas tqdm numpy requests Pillow PyYAML
RUN pip3 install opencv-python
RUN pip3 install flask_cors
RUN pip3 install werkzeug

RUN apt install -y libgl1-mesa-dev
