version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 main/main.py
    ports:
      - 80:80
    volumes:
      - ../backend:/app
    tty: True
    working_dir: /app
  slack:
    build:
      context: .
      dockerfile: ./Dockerfile #_slack
    command: python3 slack_utils/slack_send.py
    ports:
      - 90:90
    tty: true
    volumes:
      - ../backend:/app
    tty: True
    working_dir: /app
  react-app:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    volumes:
      - ../frontend:/usr/src/app
    command: yarn start
    ports:
      - 3000:3000
    stdin_open: true
